Description: Create CloudWatch Rule to Run Step Function
Parameters:
  Target:
    Description: ARN of the target function
    Type: String
  TargetName:
    Description: A name to identify the target
    Type: String
  Role:
    Description: ARN of the IAM Role to use
    Type: String
  Name:
    Description: Rule name
    Type: String
Resources:
  HourlyEvent:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: !Ref Name
      RoleArn: !Ref Role
      ScheduleExpression: 'cron(0 0/1 ? * * *)'
      State: DISABLED
      Targets:
        - Arn: !Ref Target
          Id: !Ref TargetName
          RoleArn: !Ref Role
    
