Description: Create IAM Roles and Policies
Resources:
  DataLakeGlueRole:
    Type: 'AWS::IAM::Role'
    Properties:
        Path: '/service-role/'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - glue.amazonaws.com
              Action:
                - 'sts:AssumeRole'
  DataLakeFirehoseRole:
    Type: 'AWS::IAM::Role'
    Properties:
        Path: '/service-role/'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - firehose.amazonaws.com
              Action:
                - 'sts:AssumeRole'
  DataLakeStepFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
        Path: '/service-role/'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - states.amazonaws.com
              Action:
                - 'sts:AssumeRole'
  DataLakeEventsRole:
    Type: 'AWS::IAM::Role'
    Properties:
        Path: '/service-role/'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - events.amazonaws.com
              Action:
                - 'sts:AssumeRole'
  DataLakeGlueRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: DataLakeGluePolicy
      Roles: [!Ref DataLakeGlueRole]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListAllMyBuckets'
              - 's3:CreateBucket'
              - 's3:ListBucket'
              - 's3:DeleteObject'
              - 's3:DeleteBucket'
              - 's3:GetBucketLocation'
              - 's3:GetBucketAcl'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'glue:*'
              - 'ec2:DescribeVpcEndpoints'
              - 'ec2:DescribeRouteTables'
              - 'ec2:CreateNetworkInterface'
              - 'ec2:DeleteNetworkInterfaces'
              - 'ec2:DescribeNetworkInterfaces'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeSubnets'
              - 'ec2:DescribeVpcAttribute'
              - 'iam:ListRolePolicies'
              - 'iam:GetRole'
              - 'iam:GetRolePolicy'
              - 'cloudwatch:PutMetricData'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: 'arn:aws:logs:*:*:/aws-glue/*'
          - Effect: Allow
            Action:
              - 'ec2:CreateTags'
              - 'ec2:DeleteTags'
            Resource:
              - 'arn:aws:ec2:*:*:network-interface/*'
              - 'arn:aws:ec2:*:*:security-group/*'
              - 'arn:aws:ec2:*:*:instance/*'
  DataLakeFirehoseRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: DataLakeFirehosePolicy
      Roles: [!Ref DataLakeFirehoseRole]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'glue:GetTable'
              - 'glue:GetTableVersion'
              - 'glue:GetTableVersions'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource: '*'
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
              - lambda:GetFunctionConfiguration
            Resource: '*'
          - Effect: Allow
            Action:
              - 'kms:GenerateDataKey'
              - 'kms:Decrypt'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'logs:PutLogEvents'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'Kinesis:DescribeStream'
              - 'Kinesis:GetShardIterator'
              - 'Kinesis:GetRecords'
              - 'Kinesis:ListShards'
            Resource: '*'
  DataLakeStepFunctionRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: DataLakeStepFunctionPolicy
      Roles: [!Ref DataLakeStepFunctionRole]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'glue:StartJobRun'
              - 'glue:GetJobRun'
              - 'glue:GetJobRuns'
              - 'glue:BatchStopJobRun'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'athena:startQueryExecution'
              - 'athena:stopQueryExecution'
              - 'athena:getQueryExecution'
              - 'athena:getDataCatalog'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:ListMultipartUploadParts'
              - 's3:AbortMultipartUpload'
              - 's3:CreateBucket'
              - 's3:PutObject'
            Resource: 'arn:aws:s3:::*'
          - Effect: Allow
            Action:
              - 'glue:CreateDatabase'
              - 'glue:GetDatabase'
              - 'glue:GetDatabases'
              - 'glue:UpdateDatabase'
              - 'glue:DeleteDatabase'
              - 'glue:CreateTable'
              - 'glue:UpdateTable'
              - 'glue:GetTable'
              - 'glue:GetTables'
              - 'glue:DeleteTable'
              - 'glue:BatchDeleteTable'
              - 'glue:BatchCreatePartition'
              - 'glue:CreatePartition'
              - 'glue:GetPartitions'
              - 'glue:BatchGetPartition'
              - 'glue:DeletePartition'
              - 'glue:BatchDeletePartition'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'lakeformation:GetDataAccess'
            Resource: '*'
  DataLakeEventsRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: DataLakeEventsPolicy
      Roles: [!Ref DataLakeEventsRole]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'states:StartExecution'
            Resource: '*'