- hosts: Jenkins
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Update Packages
      yum:
        name: '*'
        state: latest

    - name: Download Jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    
    - name: Import a key file from Jenkins-CI
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins and Git
      yum:
        name:
          - jenkins
          - java-1.8.0-openjdk-devel
          - git

    - name: Start Jenkins as a Service
      systemd:
        name: jenkins
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Sleep for 30 seconds
      wait_for: timeout=30

    - name: Get Jenkins Password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: no
      register: password

    - name: Print Jenkins password
      debug:
        var: password.stdout

    - name: Install python3
      yum:
        name: python3
    
    - name: Install taskcat
      pip:
        name: taskcat
        executable: pip3
